#!/usr/bin/env python3
"""
SNES-IDE - get-snes-ide-home (wrapper)
This wrapper is a convenience executable created from get-snes-ide-home.py
It allows tools and scripts to call `./get-snes-ide-home` directly on POSIX systems.
"""

from pathlib import Path
import sys

def get_executable_path() -> Path:
        """Get the path of the executable or script based on whether the script is frozen 
        (PyInstaller) or not."""

        if getattr(sys, 'frozen', False):
            print("executable path mode chosen")
            return Path(sys.executable).resolve().parent
        
        else:
            print("Python script path mode chosen")
            return Path(__file__).resolve().parent

if __name__ == "__main__":

    snes_ide_home: Path = get_executable_path().parent
    print(snes_ide_home)
