from __future__ import annotations

from rich.syntax import Syntax
from textual.widgets import Static
from textual.reactive import reactive

from ..logic.exporter import SNESExporter
from ..logic.graphics import SNESTile, SNESPalette

class AssemblyPreviewPanel(Static):
    """Displays live assembly preview of the current asset."""
    
    DEFAULT_CSS = """
    AssemblyPreviewPanel {
        width: 100%;
        height: 100%;
        background: $surface;
        border-left: solid $primary;
        padding: 0 1;
        overflow: auto;
    }
    """
    
    def update_preview(self, tile: SNESTile | None, palette: SNESPalette | None, tile_index: int) -> None:
        """Update the assembly preview."""
        if not tile or not palette:
            self.update("")
            return
            
        # Generate Tile Data
        tile_bytes = SNESExporter.tile_to_bitplanes(tile)
        tile_asm = SNESExporter.format_asm(tile_bytes, f"Tile_{tile_index:02X}")
        
        # Generate Palette Data (just the first palette for now)
        pal_bytes = SNESExporter.palette_to_bytes(palette)
        # Just show first palette (32 bytes for 4bpp)
        pal_size = palette.colors_per_palette * 2
        pal_asm = SNESExporter.format_asm(pal_bytes[:pal_size], "Palette_00")
        
        full_text = f"; SNES Asset Preview\n; Generated by SNES-IDE\n\n{tile_asm}\n\n{pal_asm}"
        
        syntax = Syntax(full_text, "asm", theme="monokai", line_numbers=True)
        self.update(syntax)
