name: Build Automatizer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    name: Build Windows automatizer.exe
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build with PyInstaller (onefile)
        run: |
          python3 scripts/pyinstaller_build_helper.py --src src/libs/pvsneslib/devkitsnes/automatizer.py --name automatizer --onefile || exit 1

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: automatizer-windows
          path: dist/automatizer.exe

  build-macos:
    name: Build macOS automatizer
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build with PyInstaller (onefile)
        run: |
          python3 scripts/pyinstaller_build_helper.py --src src/libs/pvsneslib/devkitsnes/automatizer.py --name automatizer --onefile || exit 1

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: automatizer-macos
          path: dist/automatizer

  build-linux:
    name: Build Linux automatizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build with PyInstaller (onefile)
        run: |
          python3 scripts/pyinstaller_build_helper.py --src src/libs/pvsneslib/devkitsnes/automatizer.py --name automatizer --onefile || exit 1

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: automatizer-linux
          path: dist/automatizer
