name: CI

on:
  push:
    branches: [ main, feat/**, devel, bugfix/** ]
    tags: ['v*']
  pull_request:
    branches: [ main, devel ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run INSTALL.bat
      run: .\INSTALL.bat