name: Linux Build and Test
on:
  push:
    branches: [ develop , main , linux/* ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Do Nothing Yet
      run: echo "This is a placeholder"

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
