name: Build (Windows)

# Trigger the workflow on pushes and pull‑requests to the default branch
on:
  push:
    branches: [ windows/** ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, devel ]

jobs:
  windows-build:
    name: Build on Windows
    runs-on: windows-2025 # `windows-latest` is being replaced with windows-2025, pre-empt future deprecations
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PyInstaller
        run: |
          pip install pyinstaller
        shell: cmd

      - name: Build
        run: |
          python build\build.py
        shell: cmd

      - name: Verify
        run: |
          cd "${{ github.workspace }}"
          if not exist "SNES-IDE-out" (
            echo "Build artifact not found!"
            exit 1
          )
        shell: cmd

      - name: Compress
        run: |
          cd "${{ github.workspace }}"
          powershell Compress-Archive -Path SNES-IDE-out\* -DestinationPath sneside-windows.zip -Force
        shell: pwsh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sneside-windows
          path: sneside-windows.zip
          retention-days: 7
    
  windows-test:
    name: Test (Windows)
    runs-on: windows-2025
    needs: windows-build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sneside-windows
      
      - name: Extract sneside-windows.zip
        run: |
          powershell Expand-Archive -Path sneside-windows.zip -DestinationPath sneside-windows -Force
        shell: pwsh

      - name: Check expected .exe files
        run: |
          $ErrorActionPreference = "Stop"
          $expected = @(
            "SNES-IDE.exe",
            "tools\assembler.exe",
            "tools\tracker.exe",
            "tools\soundconv.exe"
          )
          $missing = @()
          foreach ($exe in $expected) {
            if (-not (Test-Path "sneside-windows\$exe")) {
              Write-Host "Missing: $exe"
              $missing += $exe
            }
          }
          if ($missing.Count -gt 0) {
            Write-Error "Missing expected .exe files: $($missing -join ', ')"
            exit 1
          } else {
            Write-Host "All expected .exe files found."
          }
        shell: pwsh