name: Build (Windows)

# Trigger the workflow on pushes and pull‑requests to the default branch
on:
  push:
    branches: [ windows/** ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, devel ]

jobs:
  windows-build:
    name: Build on Windows
    runs-on: windows-2025 # `windows-latest` is being replaced with windows-2025, pre-empt future deprecations
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install extra build tools and venv
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install -r build-requirements.txt

      - name: Build
        run: |
          cmd /c build\build.bat
        shell: cmd

      - name: Verify
        run: |
          cd "${{ github.workspace }}"
          if not exist "SNES-IDE-out" (
            echo "Build artifact not found!"
            exit 1
          )
        shell: cmd

      - name: Compress
        run: |
          cd "${{ github.workspace }}"
          powershell Compress-Archive -Path SNES-IDE-out\* -DestinationPath sneside-windows.zip -Force
        shell: pwsh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sneside-windows
          path: sneside-windows.zip
          retention-days: 7
